$ErrorActionPreference = 'Continue'
Write-Host '==== Step 1: redeploy gcc-api ===='
& 'C:\GCC_LLC\Repos\gcc-api\publish.ps1'
Write-Host ''
Write-Host '==== Step 2: sync gcc-site (initial run) ===='
& 'C:\GCC_LLC\Repos\gcc-site\publish.ps1'
Write-Host ''
Write-Host '==== Step 3: register GCC-Site-Sync scheduled task ===='
& 'C:\ProgramData\GCC\scripts\setup_gcc_site_autosync.ps1'
